import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer } from "@/components/sections/footer";
import { Header } from "@/components/sections/header";
import { BookOnlineButton } from "@/components/ui/book-online-button";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { getBlogPost, blogPosts } from "@/content/blog-posts";

type Props = { params: Promise<{ slug: string }> };
const baseUrl = "https://www.daplappliance.com";
const formatDate = (date: string) => new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric" }).format(new Date(`${date}T12:00:00`));

export function generateStaticParams() { return blogPosts.map(({ slug }) => ({ slug })); }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const post = getBlogPost((await params).slug);
  if (!post) return {};
  return { title: post.title, description: post.description, alternates: { canonical: `/blog/${post.slug}` }, openGraph: { title: post.title, description: post.description, url: `/blog/${post.slug}`, type: "article", publishedTime: `${post.publishedAt}T12:00:00.000Z`, modifiedTime: `${post.updatedAt}T12:00:00.000Z`, authors: ["DAPL Appliance Repair"], images: [{ url: post.image, alt: post.imageAlt }] } };
}

export default async function BlogPostPage({ params }: Props) {
  const post = getBlogPost((await params).slug);
  if (!post) notFound();
  const articleUrl = `${baseUrl}/blog/${post.slug}`;
  const articleSchema = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.description, image: `${baseUrl}${post.image}`, datePublished: `${post.publishedAt}T12:00:00.000Z`, dateModified: `${post.updatedAt}T12:00:00.000Z`, mainEntityOfPage: { "@type": "WebPage", "@id": articleUrl }, author: { "@type": "Organization", name: "DAPL Appliance Repair" }, publisher: { "@type": "Organization", name: "DAPL Appliance Repair", logo: { "@type": "ImageObject", url: `${baseUrl}/logo.jpg` } } };
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: baseUrl }, { "@type": "ListItem", position: 2, name: "Blog", item: `${baseUrl}/blog` }, { "@type": "ListItem", position: 3, name: post.category, item: `${baseUrl}/blog` }, { "@type": "ListItem", position: 4, name: post.title, item: articleUrl }] };
  return <div className="min-h-screen bg-background text-foreground"><Header logoHref="/" /><main><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Blog", href: "/blog" }, { label: post.category, href: "/blog" }, { label: post.title }]} />
    <article><header className="relative overflow-hidden bg-surface py-14 sm:py-20"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(15,42,86,0.12),_transparent_34%),radial-gradient(circle_at_bottom_left,_rgba(207,36,49,0.08),_transparent_32%)]" /><div className="container-shell relative"><div className="mx-auto max-w-4xl text-center"><p className="text-sm font-bold uppercase tracking-[0.2em] text-primary">{post.category}</p><h1 className="mt-4 text-4xl font-black tracking-tight text-foreground sm:text-5xl lg:text-6xl">{post.title}</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-muted">{post.intro}</p><p className="mt-6 text-sm font-semibold text-muted">Published {formatDate(post.publishedAt)} · {post.readingTime}</p></div><div className="relative mx-auto mt-10 aspect-[16/9] max-w-6xl overflow-hidden rounded-3xl border border-border shadow-xl shadow-primary/15"><Image src={post.image} alt={post.imageAlt} fill priority sizes="(min-width: 1280px) 1120px, 94vw" className="object-cover" /></div></div></header>
      <div className="container-shell grid gap-10 py-14 lg:grid-cols-[220px_minmax(0,760px)] lg:justify-center lg:py-20"><aside className="hidden lg:block"><div className="sticky top-28 rounded-2xl border border-border bg-surface p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-primary">In this guide</p><ol className="mt-4 space-y-3 text-sm leading-5 text-muted">{post.sections.map((section, index) => <li key={section.heading}><a href={`#section-${index + 1}`} className="transition hover:text-primary">{section.heading}</a></li>)}</ol></div></aside><div className="min-w-0"><div className="rounded-2xl border border-primary/15 bg-primary/[0.04] p-5 text-sm leading-7 text-foreground"><strong className="block text-primary">Safety first</strong>{post.safetyNote}</div>{post.sections.map((section, index) => <section id={`section-${index + 1}`} key={section.heading} className="scroll-mt-32 border-b border-border py-9 first:pt-10 last:border-b-0"><h2 className="text-3xl font-black tracking-tight text-foreground">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-5 text-[1.02rem] leading-8 text-muted">{paragraph}</p>)}{section.bullets ? <ul className="mt-5 space-y-3 rounded-2xl bg-[#f2f5f9] p-5 text-sm leading-7 text-foreground">{section.bullets.map((bullet) => <li key={bullet} className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-accent" />{bullet}</li>)}</ul> : null}</section>)}
        <section className="rounded-3xl border border-accent/30 bg-accent/[0.1] p-6 sm:p-8"><p className="text-sm font-black uppercase tracking-[0.16em] text-primary">When to call a professional</p><h2 className="mt-3 text-2xl font-black tracking-tight text-foreground">Get help before a small symptom becomes a bigger interruption.</h2><ul className="mt-5 space-y-3 text-sm leading-7 text-foreground">{post.professionalHelp.map((item) => <li key={item} className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-primary" />{item}</li>)}</ul></section>
        <section className="mt-12"><p className="text-sm font-black uppercase tracking-[0.16em] text-primary">Related local repair pages</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{post.relatedLinks.map((link) => <Link key={link.href} href={link.href} className="rounded-2xl border border-border bg-surface p-4 text-sm font-bold text-primary transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md">{link.label} <span aria-hidden>→</span></Link>)}</div></section>
        <section className="mt-14"><p className="text-sm font-black uppercase tracking-[0.16em] text-primary">FAQ</p><h2 className="mt-3 text-3xl font-black tracking-tight text-foreground">Common questions</h2><div className="mt-6 space-y-3">{post.faqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-border bg-surface p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-foreground"><span>{faq.question}</span><span className="text-primary transition group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-7 text-muted">{faq.answer}</p></details>)}</div></section>
      </div></div>
      <section className="bg-primary py-16 text-primary-foreground"><div className="container-shell flex flex-col items-start justify-between gap-7 lg:flex-row lg:items-center"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-white/70">DAPL Appliance Repair</p><h2 className="mt-3 text-3xl font-black tracking-tight">Need local appliance repair?</h2><p className="mt-3 leading-7 text-white/85">Tell us what the appliance is doing. We serve Charlotte, Mint Hill, and nearby communities, with appointment availability based on the route and schedule.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="tel:+19803936588" className="inline-flex items-center justify-center rounded-full bg-accent px-6 py-3 text-sm font-black text-accent-foreground transition hover:brightness-95">Call +1 (980) 393-6588</a><BookOnlineButton location={`blog_${post.slug}_cta`} className="rounded-full border border-white/25 bg-white/10 px-6 py-3 text-sm font-black text-primary-foreground transition hover:bg-white/15" /></div></div></section>
    </article></main><Footer /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} /></div>;
}
