export const blogCategories = [
  "Refrigerator",
  "Laundry",
  "Kitchen Appliances",
  "Maintenance",
  "Repair vs. Replace",
  "Local Charlotte Advice",
] as const;

export type BlogCategory = (typeof blogCategories)[number];

export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  category: BlogCategory;
  publishedAt: string;
  updatedAt: string;
  readingTime: string;
  image: string;
  imageAlt: string;
  intro: string;
  sections: { heading: string; paragraphs: string[]; bullets?: string[] }[];
  professionalHelp: string[];
  safetyNote: string;
  faqs: { question: string; answer: string }[];
  relatedLinks: { label: string; href: string }[];
};

const date = "2026-09-02";

export const blogPosts: BlogPost[] = [
  {
    slug: "refrigerator-not-cooling-common-causes",
    title: "Why Is My Refrigerator Not Cooling? 7 Common Causes",
    description: "Learn the common reasons a refrigerator stops cooling, the safe checks homeowners can make, and when to call for refrigerator repair in Charlotte, NC.",
    category: "Refrigerator", publishedAt: date, updatedAt: date, readingTime: "8 min read",
    image: "/blog/refrigerator-not-cooling.webp", imageAlt: "Open stainless refrigerator in a bright Charlotte kitchen during a cooling check",
    intro: "A refrigerator that is warmer than usual can put groceries at risk quickly. Before assuming the appliance has failed, take note of what is still cold, whether the freezer is affected, and whether you see frost, water, or a new sound. Those details can point toward the right next step.",
    sections: [
      { heading: "Start with the simple conditions", paragraphs: ["Confirm the temperature controls were not bumped and that the doors are closing fully. A crowded shelf, a package against the door, or a worn-looking gasket can leave a small gap that lets warm kitchen air in. Give the refrigerator room around interior vents too; cold air needs a path to move between compartments.", "If cooling changed after a power outage, a move, or a very warm day, give the appliance time to stabilize after restoring normal settings. Check the outlet and breaker only if you can do so safely. A refrigerator that has no lights, no fan sound, or repeated power loss needs professional attention rather than repeated resets."], bullets: ["Keep interior vents clear of food containers.", "Check that doors close without resistance.", "Use a separate refrigerator thermometer if the display seems unreliable."] },
      { heading: "Seven common causes of weak cooling", paragraphs: ["Blocked condenser airflow is a common reason for poor performance. Dust and pet hair can collect around the lower or rear intake, making it harder for the system to release heat. A dirty condenser is often a maintenance issue, while a damaged fan, compressor, control, or sealed cooling system needs diagnosis.", "Other common causes include a failed evaporator fan, frost blocking airflow, a defrost-system issue, a bad door gasket, a temperature sensor or control problem, and a clogged drain that leaves water or ice where it should not be. The same symptom can have more than one cause, so it is better to document the behavior than replace parts by guesswork."], bullets: ["Freezer cold but refrigerator warm can suggest an airflow or defrost issue.", "Both sections warm can point to a broader cooling or control problem.", "Heavy frost, water leaks, clicking, or repeated cycling are useful details to share."] },
      { heading: "Protect food while you decide", paragraphs: ["Limit door openings and move perishable food to a working refrigerator or insulated cooler with ice if temperatures are rising. Do not rely on smell alone to decide whether food is safe. Follow current food-safety guidance for anything that has been held above a safe temperature for too long.", "Avoid chipping ice with sharp tools, forcing frozen panels open, or trying to access sealed refrigerant tubing. These can cause injuries, pierce a line, or turn a repairable issue into a bigger one. If you see an oily residue, smell something unusual, or hear persistent clicking, leave the appliance unplugged only if it is safe to do so and arrange an inspection."], },
      { heading: "When a repair visit makes sense", paragraphs: ["A technician can distinguish between airflow, defrost, electrical-control, and sealed-system problems with the right tools. Bring the model number, the approximate age of the appliance, when the problem started, and a short list of symptoms. That helps make the visit more efficient and supports a practical repair-versus-replace conversation.", "For Charlotte homeowners, a refrigerator that is not cooling is usually worth addressing promptly because food loss can add up. DAPL Appliance Repair can help with common refrigerator concerns in Charlotte and nearby service areas, subject to scheduling availability."], },
    ], professionalHelp: ["The refrigerator is warm in both compartments.", "You notice heavy frost, water pooling, burning smells, or repeated clicking.", "The unit has a no-cool condition after basic airflow and door checks."], safetyNote: "Do not open electrical panels, pierce ice, or attempt refrigerant work. Refrigerators contain energized components and sealed systems that require trained service.",
    faqs: [{ question: "Can a dirty condenser make a refrigerator warm?", answer: "It can reduce heat release and make the appliance work harder. Cleaning accessible dust safely may help, but it will not correct a failed fan, control, compressor, or sealed-system fault." }, { question: "Why is my freezer cold but my refrigerator warm?", answer: "That pattern often involves air movement or defrosting, but the exact cause depends on the model and symptoms. A focused diagnosis is the safest way to avoid replacing the wrong part." }],
    relatedLinks: [{ label: "Refrigerator repair in Charlotte", href: "/refrigerator-repair-charlotte-nc" }, { label: "Charlotte appliance repair", href: "/appliance-repair-charlotte-nc" }, { label: "Whirlpool refrigerator repair", href: "/brands/whirlpool-appliance-repair-charlotte-nc" }],
  },
  {
    slug: "dryer-taking-too-long-to-dry", title: "Dryer Taking Too Long to Dry? What Charlotte Homeowners Should Check", description: "Understand common reasons a dryer takes too long to dry, safe homeowner checks, and warning signs that call for professional dryer repair.", category: "Local Charlotte Advice", publishedAt: date, updatedAt: date, readingTime: "8 min read", image: "/blog/dryer-taking-too-long.webp", imageAlt: "Front-loading dryer and lint filter in a bright laundry room", intro: "When a dryer runs for a full cycle but clothes stay damp, the problem is often related to airflow, heat, moisture sensing, or the load itself. The safest first step is to avoid running cycle after cycle until you know why performance changed.",
    sections: [
      { heading: "Check the lint screen every load", paragraphs: ["A lint screen can look clean while a thin film from dryer sheets or detergent residue restricts airflow. Remove lint after every load, then wash the screen occasionally with warm water and mild soap if it feels coated. Let it dry completely before reinstalling it.", "Look at the exterior vent while the dryer is running. Air should move freely outside. Weak airflow can mean a crushed transition duct, a blocked exterior hood, a long vent run, or lint deeper in the system. Because lint is combustible, do not treat poor airflow as a minor inconvenience."], bullets: ["Clean the lint screen after every cycle.", "Keep the area around the dryer free of stored items.", "Never run the dryer without its lint filter in place."] },
      { heading: "Load size and fabric mix matter", paragraphs: ["An overloaded drum cannot tumble clothes well, while a tiny load may not contact a moisture sensor consistently. Very heavy items such as towels, blankets, and jeans hold more water and may need a separate cycle. If one fabric type dries normally but every load takes too long, that distinction helps narrow the diagnosis.", "Try a timed-dry test with a normal-sized load. If the dryer heats during timed dry but automatic cycles end early, the sensor or its surrounding conditions may be involved. If there is no heat, weak heat, unusual odor, or the cycle repeatedly stops, do not open the appliance to investigate."], },
      { heading: "Heat and airflow problems can look alike", paragraphs: ["Electric and gas dryers have different heating systems, but both depend on safe airflow. A dryer may tumble normally while a heating element, thermostat, igniter, gas-valve component, sensor, or control develops a fault. Vent restriction can also cause overheating and shortened component life.", "Do not use a dryer with a burning smell, excessive cabinet heat, a tripping breaker, a gas odor, or visible damage to the cord or vent connection. Turn it off and arrange qualified service. For gas appliances, leave the area and follow your gas provider's safety guidance if you smell gas."], },
      { heading: "Plan a useful service call", paragraphs: ["Note whether the drum turns, whether clothes ever get warm, how long a typical load takes, and whether the exterior vent is moving air. Include the dryer brand and model when booking. Those details help a technician prepare for common dryer and vent-related issues.", "DAPL Appliance Repair helps Charlotte-area homeowners with dryer issues when availability allows. A quick professional diagnosis can clarify whether the concern is appliance heating, sensing, airflow, or a combination of factors."], },
    ], professionalHelp: ["The dryer smells hot or burning, trips a breaker, or shows visible damage.", "The exterior vent has little airflow or you suspect a blocked duct.", "The dryer tumbles but produces no heat or stops mid-cycle."], safetyNote: "Do not remove dryer panels, bypass thermal safety devices, or work on gas connections. Lint, high voltage, and gas components can create serious fire and safety risks.", faqs: [{ question: "Why does my dryer take two or three cycles?", answer: "Restricted venting, a coated lint screen, weak heat, oversized loads, or moisture-sensor issues can all cause long dry times. The pattern of heat and airflow helps identify the likely cause." }, { question: "Can a blocked dryer vent be dangerous?", answer: "Yes. Lint and restricted airflow can cause overheating and increase fire risk. Stop using the dryer if airflow is weak or you notice unusual heat or odors." }], relatedLinks: [{ label: "Dryer repair in Charlotte", href: "/dryer-repair-charlotte-nc" }, { label: "Appliance repair in Matthews", href: "/appliance-repair-matthews-nc" }, { label: "LG appliance repair", href: "/brands/lg-appliance-repair-charlotte-nc" }],
  },
  {
    slug: "clean-dishwasher-filter-and-repair-signs", title: "How to Clean a Dishwasher Filter and When It Needs Repair", description: "A practical guide to cleaning an accessible dishwasher filter, preventing odors and poor cleaning, and recognizing signs that need professional repair.", category: "Kitchen Appliances", publishedAt: date, updatedAt: date, readingTime: "7 min read", image: "/blog/dishwasher-filter-cleaning.webp", imageAlt: "Dishwasher filter being rinsed in a clean kitchen", intro: "A dishwasher filter catches food particles before they circulate through the machine. On models with a removable filter, regular cleaning can improve cleaning performance and reduce odors. It cannot fix every dishwasher problem, but it is one of the most useful safe maintenance tasks for homeowners.",
    sections: [
      { heading: "Find out whether your filter is removable", paragraphs: ["Many modern dishwashers have a cylindrical or flat filter below the lower rack. The owner's manual is the best guide because filter designs and removal steps vary by model. Do not force a part that does not turn or lift easily; some components are not intended for routine removal.", "Before cleaning, let the dishwasher cool and remove the lower rack carefully. Lift out loose debris around the filter area with a soft cloth. If you see broken glass, use appropriate protection and avoid reaching into areas you cannot see clearly."], },
      { heading: "Clean the filter gently", paragraphs: ["Rinse a removable filter under warm running water. A soft brush can remove trapped food from the fine mesh without damaging it. Avoid harsh cleaners, metal tools, and aggressive scraping. Once clean, reinstall the filter exactly as the manual describes; a loose or incorrectly seated filter can create new problems.", "Wipe the door gasket and check spray arms for visible debris only if your model allows easy access. Use a dishwasher cleaner only according to its instructions. More detergent is not always better: excess detergent can leave film, especially with hard water or an incorrect cycle selection."], bullets: ["Run the kitchen tap hot before starting a cycle when practical.", "Load dishes so spray arms can rotate freely.", "Clean the filter more often after heavily soiled loads."] },
      { heading: "Know the limits of cleaning", paragraphs: ["A clean filter will not repair a failed drain pump, circulation motor, water inlet issue, heater, sensor, latch, or control. Standing water, leaks, grinding, repeated error codes, or dishes that remain dirty after normal maintenance may need a diagnosis. Record where water is collecting and when in the cycle the issue appears.", "Never mix cleaning products or pour drain chemicals into a dishwasher. Those products can damage seals, internal parts, and plumbing, and they create a hazard for anyone servicing the appliance. If there is a leak near cabinetry or flooring, stop the cycle and protect the area from further water exposure."], },
      { heading: "When to schedule dishwasher repair", paragraphs: ["Call for service if the machine will not drain, leaks consistently, makes loud mechanical noises, smells electrically hot, or stops during a cycle. Share the brand, model, error code if present, and the exact symptom. That gives the technician a clearer starting point.", "DAPL Appliance Repair serves Charlotte and nearby communities with dishwasher repair help when scheduling allows. Routine filter care can keep a dishwasher cleaner, while professional service can address the mechanical or electrical issues behind persistent performance problems."], },
    ], professionalHelp: ["Standing water remains after a completed cycle.", "The dishwasher leaks, makes grinding noises, or has a burning smell.", "Cleaning results do not improve after basic maintenance and correct loading."], safetyNote: "Disconnect power only if you can do so safely, and do not use chemical drain cleaners in the dishwasher. Water, electrical parts, and sharp debris require caution.", faqs: [{ question: "How often should I clean a dishwasher filter?", answer: "It depends on how often the dishwasher runs and how much food reaches it. Check the manual and inspect it more often if you notice odor, residue, or poor cleaning." }, { question: "Why is there water in the bottom after a cycle?", answer: "A filter can be part of the issue, but standing water can also involve the drain hose, pump, plumbing connection, or control. Persistent water should be diagnosed rather than treated with drain chemicals." }], relatedLinks: [{ label: "Dishwasher repair in Charlotte", href: "/dishwasher-repair-charlotte-nc" }, { label: "Appliance repair in Mint Hill", href: "/appliance-repair-mint-hill-nc" }, { label: "Bosch appliance repair", href: "/brands/bosch-appliance-repair-charlotte-nc" }],
  },
  {
    slug: "washer-wont-spin-common-causes", title: "Washer Won’t Spin: Common Causes and When to Call a Technician", description: "Find out why a washing machine may stop before spin, the safe checks to make, and when a washer needs professional repair in Charlotte.", category: "Laundry", publishedAt: date, updatedAt: date, readingTime: "8 min read", image: "/blog/washer-wont-spin.webp", imageAlt: "Front-loading washer during a professional diagnostic check", intro: "A washer that will not spin can leave a tub full of water and a load that is far too wet to dry. The cause might be as simple as an unbalanced load, but it can also involve draining, a lid or door lock, a drive component, a sensor, or the controls.",
    sections: [
      { heading: "Start with the load and the cycle", paragraphs: ["Pause the machine and redistribute bulky items if the load is all on one side. Single heavy pieces, such as a bath mat or blanket, can make a washer stop a spin cycle to protect itself. Use the cycle recommended for the fabric and avoid filling the drum beyond the manufacturer's guidance.", "If water remains in the tub, the washer may be unable to begin spinning because it has not drained. Listen for a hum, repeated clicking, or a pump sound. Do not tip the appliance or reach into a washer that still has water and power connected."], },
      { heading: "Common reasons a washer will not spin", paragraphs: ["A clogged drain path, failed drain pump, damaged belt on applicable models, worn suspension, door or lid-lock issue, motor problem, speed sensor fault, or control problem can interrupt spin. Front-load and top-load washers use different designs, so the same symptom does not always point to the same repair.", "A machine that shakes excessively may be level-related, load-related, or experiencing internal wear. Check that the washer sits firmly on the floor and that adjustable feet have not loosened. If the unit walks across the room, bangs hard, or repeatedly gives a balance error, stop using it until the cause is understood."], },
      { heading: "Avoid risky quick fixes", paragraphs: ["Do not bypass a lid switch or door lock, and do not force a locked door. These are safety components. Avoid using chemical drain cleaners in the washer or disconnecting hoses without preparing for water. A small mistake can damage flooring or create an electrical hazard.", "Write down where the cycle stops, whether water drains, which lights or codes appear, and whether the issue happens with every load. That information is more useful than running repeated test loads, especially when the washer is noisy or leaking."], },
      { heading: "What a technician needs to know", paragraphs: ["When booking washer repair, include the brand, model, load type, error code, and whether the basket or drum moves. This can help distinguish a simple balance concern from a drain, lock, motor, or control issue.", "DAPL Appliance Repair can help Charlotte-area homeowners with common washer problems when appointments are available. A careful diagnosis is especially valuable for a washer that leaves water in the tub, makes loud noises, or will not unlock normally."], },
    ], professionalHelp: ["The washer will not drain, leaks, or leaves water in the tub.", "It bangs violently, smells hot, displays repeated errors, or will not unlock.", "Load redistribution and a level floor do not resolve the spin issue."], safetyNote: "Never bypass lid or door-lock safety switches, and do not open panels around an energized appliance. Water and electrical components make washer repairs hazardous.", faqs: [{ question: "Will a washer spin if it cannot drain?", answer: "Many washers will not enter a high-speed spin while water remains in the tub. The cause may involve the drain path, pump, lock, sensor, or another part of the cycle." }, { question: "Why does my washer shake only on spin?", answer: "An uneven load or floor can contribute, but persistent strong vibration can also involve suspension, leveling, or internal drive components. Stop use if the machine moves or bangs hard." }], relatedLinks: [{ label: "Washer repair in Charlotte", href: "/washer-repair-charlotte-nc" }, { label: "Appliance repair in Concord", href: "/appliance-repair-concord-nc" }, { label: "Samsung appliance repair", href: "/brands/samsung-appliance-repair-charlotte-nc" }],
  },
  {
    slug: "oven-not-heating-evenly", title: "Oven Not Heating Evenly: Signs It May Need Professional Repair", description: "Learn why an oven may bake unevenly, simple safe checks, and the symptoms that call for professional oven repair.", category: "Kitchen Appliances", publishedAt: date, updatedAt: date, readingTime: "7 min read", image: "/blog/oven-not-heating-evenly.webp", imageAlt: "Built-in oven with unevenly baked cookies in a contemporary kitchen", intro: "Uneven baking can be frustrating because the oven may appear to preheat normally while food cooks too quickly on one side or stays underdone in the center. The pattern matters: inconsistent results can relate to rack position, cookware, airflow, temperature sensing, heating elements, igniters, or controls.",
    sections: [
      { heading: "Rule out cooking variables first", paragraphs: ["Use the rack position recommended by the recipe and leave space around pans for air to circulate. Dark, warped, oversized, or crowded cookware can change browning. Avoid opening the door repeatedly during baking, since heat loss affects small ovens especially quickly.", "If you use an oven thermometer, treat it as a clue rather than a full diagnosis. Thermometers vary, and temperatures naturally cycle around a setpoint. What matters is a persistent difference between selected temperature and baking results, especially when it appears across recipes and cookware."], },
      { heading: "Look for useful symptom patterns", paragraphs: ["Food that browns only on the bottom, only on one side, or inconsistently between racks can point to different airflow or heat sources. A long preheat, a broiler that does not work, a weak bake function, clicking, or an error code are all useful observations.", "Electric ovens may have element, sensor, relay, or control concerns. Gas ovens may involve ignition, flame, sensor, or control behavior. Because each uses high heat and electrical components, do not remove panels or attempt to test live circuits at home."], },
      { heading: "Safety signs to take seriously", paragraphs: ["Stop using the oven if you smell gas, see a damaged element, notice sparking, smell burning insulation, or have a breaker trip. For a gas odor, leave the area and follow your gas provider's emergency guidance. Do not use an open flame to test for gas.", "Self-clean cycles create extreme heat. Avoid using one to solve a performance issue or heavy residue when the oven is already behaving abnormally. Review the manufacturer's guidance and schedule service instead if the appliance has an error or a known heating concern."], },
      { heading: "Deciding on professional repair", paragraphs: ["A professional can test heating performance and identify whether the fault is mechanical, electrical, or control-related. Have the model number, fuel type, affected cooking mode, and any codes ready. That prevents a vague report about uneven heating from becoming a longer diagnosis.", "DAPL Appliance Repair helps with common oven concerns in Charlotte and nearby areas when availability allows. Professional repair is the sensible path when uneven heating is persistent, symptoms are worsening, or there is any gas or electrical safety concern."], },
    ], professionalHelp: ["Preheat is unusually slow or the oven will not reach temperature.", "You see sparking, a damaged element, a code, or smell gas or burning.", "Uneven results persist after normal rack, cookware, and recipe adjustments."], safetyNote: "Do not test gas leaks with a flame, bypass oven safety components, or work on live electrical circuits. Gas and high-heat appliance issues need trained service.", faqs: [{ question: "Can an oven thermometer tell me if my oven is broken?", answer: "It can reveal a repeatable temperature concern, but it does not identify the failed component. Compare several normal bakes and note the symptoms for a technician." }, { question: "Why does one side of my oven cook faster?", answer: "Cookware, rack placement, convection airflow, sensor performance, and heating behavior can all affect results. A persistent pattern needs a focused inspection." }], relatedLinks: [{ label: "Oven repair in Charlotte", href: "/oven-repair-charlotte-nc" }, { label: "Appliance repair in Huntersville", href: "/appliance-repair-huntersville-nc" }, { label: "GE appliance repair", href: "/brands/ge-appliance-repair-charlotte-nc" }],
  },
  {
    slug: "repair-or-replace-refrigerator", title: "Repair or Replace Your Refrigerator? A Practical Decision Guide", description: "Use age, repair scope, energy use, condition, and household needs to make a practical refrigerator repair-versus-replace decision.", category: "Repair vs. Replace", publishedAt: date, updatedAt: date, readingTime: "8 min read", image: "/blog/repair-or-replace-refrigerator.webp", imageAlt: "Homeowner comparing refrigerator repair options at a kitchen island", intro: "The right decision is rarely just about whether a refrigerator still turns on. A practical choice considers the exact failure, the age and overall condition of the appliance, the repair recommendation, food-storage needs, and whether a replacement would actually solve a bigger problem.",
    sections: [
      { heading: "Start with a diagnosis, not a guess", paragraphs: ["A refrigerator can have a minor airflow, fan, gasket, drain, ice maker, control, or defrost issue that is worth discussing as a repair. Other faults may involve more extensive cooling-system work or a unit that has already had repeated expensive problems. The symptoms alone cannot tell you which category applies.", "Ask for a clear description of what is failing, what the recommended repair addresses, and what condition is visible elsewhere in the appliance. A diagnosis gives you a real comparison point instead of deciding based on an online average that may not match your model."], },
      { heading: "Consider age and overall reliability", paragraphs: ["Age is useful context, not an automatic verdict. A well-maintained refrigerator with a contained issue can be a reasonable repair candidate. An older unit with multiple recurring problems, corrosion, damaged shelves or seals, and unstable cooling may deserve a replacement discussion.", "Think about the household cost of downtime too. If the refrigerator is essential for medications, large family grocery storage, or business use, reliability and lead time can matter as much as the repair estimate. Keep a cooler plan in mind while you decide."], },
      { heading: "Compare the full replacement cost", paragraphs: ["Replacement is more than the price on a product tag. Delivery, installation, haul-away, water-line work, trim changes, and a new appliance's fit can affect the total. Measure doorways, cabinet openings, depth, and ventilation space before assuming a new model will drop in easily.", "Energy use is another factor, but it should be part of a broader decision. A newer model may use less energy, while an otherwise sound refrigerator may still be a better short-term fit after repair. Avoid treating a single rule of thumb as universal."], },
      { heading: "Make the choice with the right questions", paragraphs: ["Useful questions include: Is this the first major repair? Is cooling stable aside from the diagnosed problem? Is the repair likely to address the current symptom? Does the household need a specific size or layout? Are there signs of wider wear? Write the answers down before making a rushed choice.", "For Charlotte-area homeowners, DAPL Appliance Repair can provide practical refrigerator repair guidance when scheduling allows. The goal of a repair visit is a clearer decision based on the appliance in front of you, not pressure toward either option."], },
    ], professionalHelp: ["The refrigerator has a repeat no-cool condition or multiple problems.", "You need to understand the exact repair scope before making a replacement purchase.", "There is frost, water, unusual noise, or inconsistent cooling affecting stored food."], safetyNote: "Do not attempt sealed-system or electrical repairs to reduce costs. Refrigerant systems, capacitors, and compressor circuitry require specialized equipment and safe handling.", faqs: [{ question: "Is it worth repairing a 10-year-old refrigerator?", answer: "It depends on the diagnosed issue, overall condition, repair scope, and replacement alternatives. Age alone does not determine whether repair makes sense." }, { question: "Should I replace a refrigerator that is not cooling?", answer: "Not before understanding the cause. Some no-cool symptoms involve repairable airflow, defrost, fan, or control issues, while others require a broader decision." }], relatedLinks: [{ label: "Refrigerator repair in Charlotte", href: "/refrigerator-repair-charlotte-nc" }, { label: "Appliance repair in Fort Mill", href: "/appliance-repair-fort-mill-sc" }, { label: "KitchenAid appliance repair", href: "/brands/kitchenaid-appliance-repair-charlotte-nc" }],
  },
  {
    slug: "prevent-appliance-breakdowns-before-holidays", title: "How to Prevent Appliance Breakdowns Before the Holiday Season", description: "A practical pre-holiday appliance maintenance checklist for Charlotte homeowners, with safe tasks and clear signs to book professional help.", category: "Maintenance", publishedAt: date, updatedAt: date, readingTime: "7 min read", image: "/blog/prevent-appliance-breakdowns.webp", imageAlt: "Appliance maintenance checklist and supplies in a warm modern kitchen", intro: "Holiday cooking, guests, and extra laundry put more demand on the appliances that already work hardest at home. A short maintenance check before the busy season can reveal simple issues early and help you decide which concerns need professional attention before they interrupt plans.",
    sections: [
      { heading: "Give the refrigerator room to work", paragraphs: ["Clear crowded vents inside the refrigerator and freezer, check door gaskets for crumbs or gaps, and make sure doors close fully. Keep the temperature steady and do not pack warm leftovers tightly into the compartment. If you can safely access the exterior intake area, remove loose dust according to the owner's manual.", "Watch for temperature swings, water under the unit, heavy frost, a struggling ice maker, or a new clicking sound. Those are better addressed before a full refrigerator becomes unreliable during a house full of groceries."], },
      { heading: "Treat dryer airflow as a safety task", paragraphs: ["Clean the lint screen after every load and inspect the outdoor vent hood for free airflow. Keep laundry items and storage away from the dryer. If dry times are increasing, do not assume the machine simply needs another cycle; airflow and heat issues can worsen under heavier holiday use.", "Do not take apart the dryer or use makeshift vent connections. If you notice a burning smell, excessive heat, weak exterior airflow, or a tripping breaker, stop using the appliance and arrange qualified service."], },
      { heading: "Make the dishwasher and oven easier on themselves", paragraphs: ["Clean an accessible dishwasher filter as directed by the manufacturer, inspect the door gasket, and load dishes so spray arms can move. Use the right detergent amount for your water and cycle. Persistent standing water, leaks, grinding, or poor cleaning after maintenance should not be ignored.", "For ovens, check racks, avoid lining the oven with foil unless the manufacturer allows it, and watch for slow preheat or uneven results before a large meal. Do not use a self-clean cycle to deal with a suspected heating or control problem."], },
      { heading: "Book ahead when a symptom is already present", paragraphs: ["Appliance problems rarely arrive at a convenient time. If a washer is failing to spin, a dryer needs repeated cycles, an oven heats inconsistently, or a freezer is frosting heavily, schedule an assessment before the demand increases. Note the model, error codes, and symptoms to make the appointment efficient.", "DAPL Appliance Repair serves Charlotte and nearby communities for many kitchen, laundry, and cooling concerns. Availability changes with the route, so early booking is the best way to explore an appointment before holiday schedules become busy."], },
    ], professionalHelp: ["A cooling appliance is changing temperature, leaking, or building heavy frost.", "A dryer has weak airflow, overheating, or a burning smell.", "An oven, dishwasher, or washer has persistent errors, leaks, or performance changes."], safetyNote: "Keep maintenance within the manufacturer-recommended homeowner tasks. Do not open electrical panels, gas connections, sealed cooling systems, or internal dryer components.", faqs: [{ question: "When should I schedule appliance maintenance before the holidays?", answer: "A few weeks before busy cooking or guest season gives you time to address an existing symptom. Do not wait if there is a safety concern, leak, or active cooling problem." }, { question: "What appliance task is most important for safety?", answer: "For many homes, consistent dryer lint and vent attention is especially important because restricted airflow can create overheating and fire risk." }], relatedLinks: [{ label: "Appliance repair in Charlotte", href: "/appliance-repair-charlotte-nc" }, { label: "Dryer repair in Charlotte", href: "/dryer-repair-charlotte-nc" }, { label: "Appliance repair in Waxhaw", href: "/appliance-repair-waxhaw-nc" }],
  },
  {
    slug: "what-to-do-when-freezer-stops-freezing", title: "What to Do When Your Freezer Stops Freezing", description: "Take the right first steps when a freezer is not freezing, protect food, and recognize signs that need professional freezer repair.", category: "Refrigerator", publishedAt: date, updatedAt: date, readingTime: "7 min read", image: "/blog/freezer-stops-freezing.webp", imageAlt: "Open freezer drawer with a homeowner checking stored food", intro: "A freezer that stops freezing is time-sensitive, but a calm first response protects food and gives you better information for a repair decision. Focus on temperature, door position, frost, sounds, and what the refrigerator compartment is doing before changing settings or trying to thaw the appliance aggressively.",
    sections: [
      { heading: "Protect food and limit door openings", paragraphs: ["Keep the door closed as much as possible while you decide whether food can be moved. Use coolers with ice or another working freezer for items that need immediate protection. Follow current food-safety guidance rather than relying only on appearance or odor when temperatures have been unstable.", "If the freezer is only slightly warmer than usual, avoid repeatedly opening it to check. Note the time you first noticed the issue and use a thermometer if available. A clear timeline helps distinguish a temporary temperature fluctuation from a sustained loss of cooling."], },
      { heading: "Check doors, airflow, and obvious frost", paragraphs: ["Make sure packages are not blocking the drawer or door and that gaskets are clean and making contact. Overpacking can reduce airflow, while a door left slightly open can introduce moisture and frost. Do not force a frozen drawer or chip ice with sharp tools.", "Heavy frost, a warm refrigerator section, a fan that is silent or unusually loud, water near the unit, and persistent clicking are all useful clues. They can relate to airflow, defrosting, controls, fans, or the cooling system, but the symptoms need diagnosis on the specific model."], },
      { heading: "Avoid common mistakes", paragraphs: ["Do not use a hair dryer, knife, heat gun, or other improvised method to remove ice. Excess heat can damage liners and wiring, and sharp tools can puncture hidden components. Do not turn controls to extreme settings in an effort to force cooling; that usually does not solve a failed part.", "If you suspect an electrical issue, smell burning, or see damaged wiring, do not continue using the appliance. If the unit is leaking water, protect the floor and nearby surfaces while waiting for service."], },
      { heading: "When freezer repair is the right next step", paragraphs: ["A professional can evaluate the machine's temperature behavior, fans, defrost components, controls, and cooling system safely. Have the model number, estimated age, food-storage symptoms, and notes about frost, water, and sound ready.", "DAPL Appliance Repair helps with common freezer and refrigerator concerns in Charlotte and nearby service areas when appointments are available. Quick action is especially valuable when the appliance has stopped freezing entirely or food is at risk."], },
    ], professionalHelp: ["The freezer is not freezing at all, or both compartments are warm.", "You have heavy frost, water leaks, persistent clicking, burning smell, or unusual noise.", "The problem returns after normal door and airflow checks."], safetyNote: "Do not pierce frost or attempt refrigerant or electrical repairs. Sharp tools and untrained work around a sealed cooling system can cause injury and permanent damage.", faqs: [{ question: "Why is my freezer cold but not freezing food?", answer: "A freezer can feel cool while its temperature is still too high for safe long-term food storage. Airflow, defrost, fan, control, and cooling issues can all be involved." }, { question: "Should I unplug a freezer that is not freezing?", answer: "Only if there is an immediate safety concern or it is safe and appropriate to do so. For food preservation, moving items to another cold source and documenting symptoms is often the first priority." }], relatedLinks: [{ label: "Freezer repair in Charlotte", href: "/freezer-repair-charlotte-nc" }, { label: "Appliance repair in Rock Hill", href: "/appliance-repair-rock-hill-sc" }, { label: "Frigidaire appliance repair", href: "/brands/frigidaire-appliance-repair-charlotte-nc" }],
  },
];

export function getBlogPost(slug: string) { return blogPosts.find((post) => post.slug === slug); }
